// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFFTQb6B3zpASJ5Dt_n68gE6KX4dRbr-8',
    appId: '1:703319951079:web:2ad8adb625adb063130442',
    messagingSenderId: '703319951079',
    projectId: 'smartpark-de50a',
    authDomain: 'smartpark-de50a.firebaseapp.com',
    storageBucket: 'smartpark-de50a.firebasestorage.app',
    measurementId: 'G-XZYS5HCEVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLV2-wl6zWLzkDk2IdzBjJhQp3sP5t_0s',
    appId: '1:703319951079:android:db98ef1034772b38130442',
    messagingSenderId: '703319951079',
    projectId: 'smartpark-de50a',
    storageBucket: 'smartpark-de50a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_YNlEMTgWQfB8AtVXs_N098kVN-SiZAM',
    appId: '1:703319951079:ios:3fcf214233b86942130442',
    messagingSenderId: '703319951079',
    projectId: 'smartpark-de50a',
    storageBucket: 'smartpark-de50a.firebasestorage.app',
    iosBundleId: 'com.example.techwizTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_YNlEMTgWQfB8AtVXs_N098kVN-SiZAM',
    appId: '1:703319951079:ios:3fcf214233b86942130442',
    messagingSenderId: '703319951079',
    projectId: 'smartpark-de50a',
    storageBucket: 'smartpark-de50a.firebasestorage.app',
    iosBundleId: 'com.example.techwizTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFFTQb6B3zpASJ5Dt_n68gE6KX4dRbr-8',
    appId: '1:703319951079:web:d3e9132c5d144427130442',
    messagingSenderId: '703319951079',
    projectId: 'smartpark-de50a',
    authDomain: 'smartpark-de50a.firebaseapp.com',
    storageBucket: 'smartpark-de50a.firebasestorage.app',
    measurementId: 'G-LBYJQ769ZT',
  );
}
